'use client'
import { useState, useEffect, useRef, useCallback } from 'react'
import type { ContentIdea, ContentCalendarEntry, BrandingProfile, SOP } from '@/types'
import { Sparkles, Loader2, Copy, Check, Download, Image as ImageIcon, Upload, X, Images, ChevronDown, ChevronRight, Save, FileText } from 'lucide-react'
import { cn } from '@/lib/utils'

interface GenerateTabProps {
  clientId: string
  ideas: ContentIdea[]
  calendar: ContentCalendarEntry[]
  prefillEntry: ContentCalendarEntry | null
  branding: BrandingProfile | null
  sops: SOP[]
  autoGenerate?: boolean
  onAutoGenerateDone?: () => void
  onCalendarChange: (calendar: ContentCalendarEntry[]) => void
}

export function GenerateTab({
  clientId,
  ideas,
  calendar,
  prefillEntry,
  branding,
  sops,
  autoGenerate,
  onAutoGenerateDone,
  onCalendarChange,
}: GenerateTabProps) {
  const [selectedIdeaId, setSelectedIdeaId] = useState(prefillEntry?.content_idea_id ?? '')
  const [selectedEntryId, setSelectedEntryId] = useState(prefillEntry?.id ?? '')
  const [useCustomPrompt, setUseCustomPrompt] = useState(false)
  const [customPrompt, setCustomPrompt] = useState('')
  const [generating, setGenerating] = useState(false)
  const [error, setError] = useState<string | null>(null)

  // Image generation is always enabled
  const generateImage = true

  // Aspect ratio — read from calendar entry (set in calendar modal)
  const imageRatio = prefillEntry?.image_ratio ?? '3:4'

  // Preview aspect class
  const RATIO_CLASS: Record<string, string> = {
    '1:1':  'aspect-square',
    '3:4':  'aspect-[3/4]',
    '9:16': 'aspect-[9/16]',
    '16:9': 'aspect-[16/9]',
    '4:3':  'aspect-[4/3]',
  }

  // Output
  const [caption, setCaption] = useState(prefillEntry?.caption ?? '')
  const [hashtags, setHashtags] = useState(prefillEntry?.hashtags ?? '')
  const [imageUrl, setImageUrl] = useState(prefillEntry?.image_url ?? '')
  const [imagePrompt, setImagePrompt] = useState('')
  const [copied, setCopied] = useState<string | null>(null)

  // ── Gem Configuration State ──
  const [gemInstructions, setGemInstructions] = useState('')
  const [gemInstructionsSaved, setGemInstructionsSaved] = useState('')
  const [gemSource, setGemSource] = useState<'local' | 'hardcoded' | 'empty'>('empty')
  const [gemLoading, setGemLoading] = useState(false)
  const [gemSaving, setGemSaving] = useState(false)
  const [gemSaveSuccess, setGemSaveSuccess] = useState(false)
  const [gemExpanded, setGemExpanded] = useState(false)

  // Reference images (Gem-like style references)
  const [refImages, setRefImages] = useState<Array<{ name: string; url: string }>>([])
  const [refLoading, setRefLoading] = useState(false)
  const [refUploading, setRefUploading] = useState(false)
  const fileInputRef = useRef<HTMLInputElement>(null)

  // ── Load Gem Config when clientId changes ──
  const loadGemConfig = useCallback(async () => {
    setGemLoading(true)
    try {
      const res = await fetch(`/api/content/gem-config?clientId=${clientId}`)
      const contentType = res.headers.get('content-type') ?? ''
      if (!contentType.includes('application/json')) {
        // Non-JSON response (e.g. auth redirect) — fall back to branding prop
        const fallback = branding?.gem_instructions ?? ''
        setGemInstructions(fallback)
        setGemInstructionsSaved(fallback)
        setGemSource(fallback ? 'hardcoded' : 'empty')
        if (!fallback) setGemExpanded(true)
        setGemLoading(false)
        return
      }
      const json = await res.json()
      if (json.ok) {
        setGemInstructions(json.instructions ?? '')
        setGemInstructionsSaved(json.instructions ?? '')
        setGemSource(json.source ?? 'empty')
        if (!json.instructions) setGemExpanded(true)
      }
    } catch {
      // Fallback to branding prop if API fails
      const fallback = branding?.gem_instructions ?? ''
      setGemInstructions(fallback)
      setGemInstructionsSaved(fallback)
      setGemSource(fallback ? 'hardcoded' : 'empty')
    }
    setGemLoading(false)
  }, [clientId, branding?.gem_instructions])

  useEffect(() => { loadGemConfig() }, [loadGemConfig])

  // ── Save Gem Config ──
  async function handleSaveGemConfig() {
    setGemSaving(true)
    setGemSaveSuccess(false)
    try {
      const res = await fetch('/api/content/gem-config', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ clientId, instructions: gemInstructions }),
      })
      const contentType = res.headers.get('content-type') ?? ''
      if (!contentType.includes('application/json')) {
        setError('Save failed — please refresh and try again')
        setGemSaving(false)
        return
      }
      const json = await res.json()
      if (json.ok) {
        setGemInstructionsSaved(gemInstructions)
        setGemSource('local')
        setGemSaveSuccess(true)
        setTimeout(() => setGemSaveSuccess(false), 2000)
      } else {
        setError(json.error ?? 'Failed to save instructions')
      }
    } catch {
      setError('Failed to save instructions')
    }
    setGemSaving(false)
  }

  const gemDirty = gemInstructions !== gemInstructionsSaved

  // ── Reference Images ──
  const loadRefImages = useCallback(async () => {
    setRefLoading(true)
    try {
      const res = await fetch(`/api/content/reference-images?clientId=${clientId}`)
      const json = await res.json()
      if (json.ok) setRefImages(json.images ?? [])
    } catch { /* ignore */ }
    setRefLoading(false)
  }, [clientId])

  useEffect(() => { loadRefImages() }, [loadRefImages])

  async function handleRefUpload(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0]
    if (!file) return
    setRefUploading(true)
    try {
      const form = new FormData()
      form.append('clientId', clientId)
      form.append('file', file)
      const res = await fetch('/api/content/reference-images', { method: 'POST', body: form })
      const json = await res.json()
      if (json.ok && json.image) {
        setRefImages(prev => [...prev, json.image])
      } else {
        setError(json.error ?? 'Upload failed')
      }
    } catch { setError('Upload failed') }
    setRefUploading(false)
    if (fileInputRef.current) fileInputRef.current.value = ''
  }

  async function handleRefDelete(fileName: string) {
    try {
      const res = await fetch('/api/content/reference-images', {
        method: 'DELETE',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ clientId, fileName }),
      })
      const json = await res.json()
      if (json.ok) setRefImages(prev => prev.filter(r => r.name !== fileName))
    } catch { /* ignore */ }
  }

  const selectedIdea = ideas.find(i => i.id === selectedIdeaId)
  const selectedEntry = calendar.find(e => e.id === selectedEntryId)

  // Prevent double-firing autoGenerate
  const autoFiredRef = useRef(false)

  // Sync when prefillEntry changes (calendar → generate navigation)
  useEffect(() => {
    if (prefillEntry) {
      setSelectedEntryId(prefillEntry.id)
      setSelectedIdeaId(prefillEntry.content_idea_id ?? '')
      setCaption(prefillEntry.caption ?? '')
      setHashtags(prefillEntry.hashtags ?? '')
      setImageUrl(prefillEntry.image_url ?? '')
      setUseCustomPrompt(false)
      autoFiredRef.current = false
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [prefillEntry?.id])

  // Auto-trigger generation when navigated from calendar
  useEffect(() => {
    if (autoGenerate && prefillEntry && !autoFiredRef.current) {
      autoFiredRef.current = true
      onAutoGenerateDone?.()
      const timer = setTimeout(() => triggerGenerate(prefillEntry), 150)
      return () => clearTimeout(timer)
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [autoGenerate, prefillEntry?.id])

  async function triggerGenerate(entry?: ContentCalendarEntry) {
    const activeEntry = entry ?? selectedEntry
    const activeIdea = selectedIdea ?? activeEntry?.idea
    if (!useCustomPrompt && !activeIdea && !activeEntry) return
    if (useCustomPrompt && !customPrompt.trim()) return

    setGenerating(true)
    setError(null)

    const effectiveTitle = useCustomPrompt ? customPrompt.trim() : (activeIdea?.title ?? 'General post')
    const effectiveDescription = useCustomPrompt ? customPrompt.trim() : (activeIdea?.description ?? '')
    const effectiveEntryId = entry?.id ?? selectedEntryId

    try {
      const res = await fetch('/api/content/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          clientId,
          entryId: effectiveEntryId || undefined,
          ideaTitle: effectiveTitle,
          ideaDescription: effectiveDescription,
          platform: activeEntry?.platform ?? activeIdea?.platform?.[0] ?? 'Instagram',
          generateImage,
          imageRatio,
          gemInstructions: gemInstructions || branding?.gem_instructions || '',
          brandLogoUrl: branding?.logo_url ?? '',
        }),
      })
      const json = await res.json()
      if (!json.ok) throw new Error(json.error)

      setCaption(json.caption ?? '')
      setHashtags(json.hashtags ?? '')
      if (json.imageUrl) setImageUrl(json.imageUrl)
      if (json.imagePrompt) setImagePrompt(json.imagePrompt)
      if (json.imageError) setError(`Image: ${json.imageError}`)

      if (effectiveEntryId) {
        onCalendarChange(calendar.map(e =>
          e.id === effectiveEntryId
            ? { ...e, caption: json.caption, hashtags: json.hashtags, status: 'generated' as const, ...(json.imageUrl ? { image_url: json.imageUrl } : {}) }
            : e,
        ))
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Generation failed')
    } finally {
      setGenerating(false)
    }
  }

  function handleGenerate() { triggerGenerate() }

  function handleCopy(text: string, label: string) {
    navigator.clipboard.writeText(text)
    setCopied(label)
    setTimeout(() => setCopied(null), 2000)
  }

  const canGenerate = useCustomPrompt ? !!customPrompt.trim() : (!!selectedIdeaId || !!selectedEntryId)

  // Gem status indicator
  const hasGemInstructions = !!gemInstructions.trim()
  const hasRefImages = refImages.length > 0

  return (
    <div className="space-y-4">
      {/* Source selection */}
      <div className="bg-white rounded-xl border border-gray-200 p-4 space-y-3">
        <div className="flex items-center justify-between">
          <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider">Source</p>
          <button
            type="button"
            onClick={() => { setUseCustomPrompt(!useCustomPrompt); if (!useCustomPrompt) { setSelectedIdeaId(''); setSelectedEntryId('') } }}
            className={cn(
              'text-[11px] font-medium px-2.5 py-1 rounded-md border transition-colors',
              useCustomPrompt
                ? 'bg-blue-50 border-blue-200 text-blue-700'
                : 'bg-gray-50 border-gray-200 text-gray-500 hover:bg-gray-100',
            )}
          >
            {useCustomPrompt ? 'Use Calendar Entry' : 'Custom Prompt'}
          </button>
        </div>

        {useCustomPrompt ? (
          <div>
            <label className="block text-[11px] font-medium text-gray-600 mb-1">Your Custom Prompt / Idea</label>
            <textarea
              value={customPrompt}
              onChange={e => setCustomPrompt(e.target.value)}
              placeholder="e.g., Create a Mobile App Development poster for Week 1, or Week 2 SaaS poster..."
              rows={3}
              className="w-full rounded-lg border border-gray-200 px-3 py-2 text-sm text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none"
            />
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div>
              <label className="block text-[11px] font-medium text-gray-600 mb-1">Select Idea</label>
              <select
                value={selectedIdeaId}
                onChange={e => setSelectedIdeaId(e.target.value)}
                className="w-full h-9 rounded-lg border border-gray-200 px-3 text-sm text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-500"
              >
                <option value="">— Choose idea —</option>
                {ideas.filter(i => i.status === 'approved').map(i => (
                  <option key={i.id} value={i.id}>{i.title}</option>
                ))}
              </select>
            </div>
            <div>
              <label className="block text-[11px] font-medium text-gray-600 mb-1">Calendar Entry (optional)</label>
              <select
                value={selectedEntryId}
                onChange={e => setSelectedEntryId(e.target.value)}
                className="w-full h-9 rounded-lg border border-gray-200 px-3 text-sm text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-500"
              >
                <option value="">— None —</option>
                {calendar.map(e => (
                  <option key={e.id} value={e.id}>
                    {e.scheduled_date} — {e.idea?.title ?? e.platform}
                  </option>
                ))}
              </select>
            </div>
          </div>
        )}

        {/* Show post draft when idea is selected */}
        {!useCustomPrompt && selectedIdea?.description && (
          <div className="bg-blue-50 rounded-lg px-3 py-2 text-[11px] text-blue-700 leading-relaxed">
            <span className="font-semibold">Post draft: </span>{selectedIdea.description}
          </div>
        )}

        <div className="flex items-center justify-between">
          {branding?.logo_url && (
            <span className="text-[10px] text-green-600 font-medium flex items-center gap-1">
              <ImageIcon className="h-3 w-3" /> Logo will be included
            </span>
          )}
          <button
            onClick={handleGenerate}
            disabled={generating || !canGenerate}
            className="flex items-center gap-2 h-9 px-5 rounded-lg bg-blue-600 text-white text-sm font-semibold hover:bg-blue-700 disabled:opacity-50 ml-auto"
          >
            {generating ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
            {generating ? 'Generating caption + image…' : 'Generate'}
          </button>
        </div>
      </div>

      {/* ── Gem Configuration (Instructions + References) ── */}
      <div className="bg-white rounded-xl border border-gray-200 overflow-hidden">
        {/* Header — always visible, clickable to toggle */}
        <button
          type="button"
          onClick={() => setGemExpanded(!gemExpanded)}
          className="w-full flex items-center justify-between px-4 py-3 hover:bg-gray-50 transition-colors"
        >
          <div className="flex items-center gap-2.5">
            <Sparkles className="h-4 w-4 text-purple-600" />
            <span className="text-xs font-semibold text-gray-700 uppercase tracking-wider">Gem Configuration</span>
            {/* Status dots */}
            <div className="flex items-center gap-1.5 ml-1">
              <span className={cn(
                'flex items-center gap-1 text-[10px] font-medium px-1.5 py-0.5 rounded',
                hasGemInstructions ? 'bg-green-50 text-green-700' : 'bg-gray-100 text-gray-400',
              )}>
                <FileText className="h-3 w-3" />
                Instructions
              </span>
              <span className={cn(
                'flex items-center gap-1 text-[10px] font-medium px-1.5 py-0.5 rounded',
                hasRefImages ? 'bg-green-50 text-green-700' : 'bg-gray-100 text-gray-400',
              )}>
                <Images className="h-3 w-3" />
                {refImages.length}/5
              </span>
            </div>
          </div>
          {gemExpanded ? <ChevronDown className="h-4 w-4 text-gray-400" /> : <ChevronRight className="h-4 w-4 text-gray-400" />}
        </button>

        {/* Collapsible content */}
        {gemExpanded && (
          <div className="border-t border-gray-200 p-4 space-y-4">
            {/* ── 1. Instructions ── */}
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <FileText className="h-3.5 w-3.5 text-purple-600" />
                  <p className="text-[11px] font-semibold text-gray-600 uppercase tracking-wider">Instructions</p>
                  {gemSource === 'hardcoded' && (
                    <span className="text-[9px] font-medium px-1.5 py-0.5 rounded bg-amber-50 text-amber-600 border border-amber-200">Template</span>
                  )}
                  {gemSource === 'local' && (
                    <span className="text-[9px] font-medium px-1.5 py-0.5 rounded bg-green-50 text-green-600 border border-green-200">Saved</span>
                  )}
                </div>
                <div className="flex items-center gap-2">
                  {gemDirty && (
                    <span className="text-[10px] text-amber-600 font-medium">Unsaved changes</span>
                  )}
                  <button
                    type="button"
                    onClick={handleSaveGemConfig}
                    disabled={gemSaving || !gemDirty}
                    className={cn(
                      'flex items-center gap-1 text-[11px] font-medium px-2.5 py-1 rounded-md border transition-colors',
                      gemSaveSuccess
                        ? 'bg-green-50 border-green-200 text-green-700'
                        : 'bg-purple-50 border-purple-200 text-purple-700 hover:bg-purple-100 disabled:opacity-50',
                    )}
                  >
                    {gemSaving ? <Loader2 className="h-3 w-3 animate-spin" /> : gemSaveSuccess ? <Check className="h-3 w-3" /> : <Save className="h-3 w-3" />}
                    {gemSaveSuccess ? 'Saved!' : 'Save'}
                  </button>
                </div>
              </div>

              {gemLoading ? (
                <div className="flex items-center gap-2 text-gray-400 py-4">
                  <Loader2 className="h-3 w-3 animate-spin" />
                  <span className="text-[11px]">Loading instructions…</span>
                </div>
              ) : (
                <>
                  <textarea
                    value={gemInstructions}
                    onChange={e => setGemInstructions(e.target.value)}
                    placeholder={`Write detailed instructions for this client's visual identity…

Example:
- You are "Brand Visual Bot" — generate ultra-realistic images for [Brand Name]
- Background: Always use [color palette]
- Food/Product Presentation: [specific style rules]
- Text Overlay: [font, color, placement rules]
- Composition Styles: [list rotation styles]
- What to never do: [hard rules]
- Official menu / product list: [items]`}
                    rows={10}
                    className="w-full rounded-lg border border-gray-200 px-3 py-2 text-sm text-gray-900 focus:outline-none focus:ring-2 focus:ring-purple-500 resize-y font-mono leading-relaxed"
                  />
                  {gemSource === 'hardcoded' && (
                    <p className="text-[10px] text-amber-600">Using default template — edit and save to customize for this client.</p>
                  )}
                  {gemSource === 'empty' && (
                    <p className="text-[10px] text-gray-400">No instructions configured. Add your client&apos;s visual identity rules, product details, and style preferences above.</p>
                  )}
                </>
              )}
            </div>

            {/* ── 2. Style References ── */}
            <div className="space-y-2 pt-2 border-t border-gray-100">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Images className="h-3.5 w-3.5 text-purple-600" />
                  <p className="text-[11px] font-semibold text-gray-600 uppercase tracking-wider">Reference Images</p>
                  <span className="text-[10px] font-medium text-purple-600 bg-purple-50 px-1.5 py-0.5 rounded">{refImages.length}/5</span>
                </div>
                <button
                  type="button"
                  onClick={() => fileInputRef.current?.click()}
                  disabled={refUploading || refImages.length >= 5}
                  className="flex items-center gap-1 text-[11px] font-medium px-2.5 py-1 rounded-md border border-purple-200 bg-purple-50 text-purple-700 hover:bg-purple-100 disabled:opacity-50 transition-colors"
                >
                  {refUploading ? <Loader2 className="h-3 w-3 animate-spin" /> : <Upload className="h-3 w-3" />}
                  Upload
                </button>
                <input
                  ref={fileInputRef}
                  type="file"
                  accept="image/jpeg,image/png,image/webp"
                  onChange={handleRefUpload}
                  className="hidden"
                />
              </div>

              {refLoading ? (
                <div className="flex items-center gap-2 text-gray-400 py-2">
                  <Loader2 className="h-3 w-3 animate-spin" />
                  <span className="text-[11px]">Loading references…</span>
                </div>
              ) : refImages.length > 0 ? (
                <div className="grid grid-cols-5 gap-2">
                  {refImages.map(img => (
                    <div key={img.name} className="relative group">
                      <div className="aspect-square rounded-lg overflow-hidden border border-gray-200 bg-gray-50">
                        <img src={img.url} alt={img.name} className="w-full h-full object-cover" />
                      </div>
                      <button
                        type="button"
                        onClick={() => handleRefDelete(img.name)}
                        className="absolute -top-1 -right-1 h-5 w-5 rounded-full bg-red-500 text-white flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity shadow-sm"
                      >
                        <X className="h-3 w-3" />
                      </button>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="text-[10px] text-gray-400 py-1">Upload 3-5 example images to match a specific visual style. The AI will use these as reference for generated images.</p>
              )}
            </div>
          </div>
        )}
      </div>

      {error && <p className="text-sm text-red-600 bg-red-50 rounded-lg px-3 py-2">{error}</p>}

      {/* Output */}
      {(caption || imageUrl || generating) && (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
          {/* Caption & Hashtags */}
          <div className="space-y-3">
            {(caption || generating) && (
              <>
                <div className="bg-white rounded-xl border border-gray-200 p-4">
                  <div className="flex items-center justify-between mb-2">
                    <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider">Caption</p>
                    <button
                      onClick={() => handleCopy(caption, 'caption')}
                      className="flex items-center gap-1 h-6 px-2 rounded text-[10px] font-medium text-gray-500 hover:bg-gray-100"
                    >
                      {copied === 'caption' ? <Check className="h-3 w-3 text-green-500" /> : <Copy className="h-3 w-3" />}
                      {copied === 'caption' ? 'Copied!' : 'Copy'}
                    </button>
                  </div>
                  {generating && !caption ? (
                    <div className="flex items-center gap-2 text-gray-400 py-4">
                      <Loader2 className="h-4 w-4 animate-spin" />
                      <span className="text-sm">Writing caption…</span>
                    </div>
                  ) : (
                    <textarea
                      value={caption}
                      onChange={e => setCaption(e.target.value)}
                      rows={10}
                      className="w-full rounded-lg border border-gray-200 px-3 py-2 text-sm text-gray-900 focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none"
                    />
                  )}
                </div>

                <div className="bg-white rounded-xl border border-gray-200 p-4">
                  <div className="flex items-center justify-between mb-2">
                    <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider">Hashtags</p>
                    <button
                      onClick={() => handleCopy(hashtags, 'hashtags')}
                      className="flex items-center gap-1 h-6 px-2 rounded text-[10px] font-medium text-gray-500 hover:bg-gray-100"
                    >
                      {copied === 'hashtags' ? <Check className="h-3 w-3 text-green-500" /> : <Copy className="h-3 w-3" />}
                      {copied === 'hashtags' ? 'Copied!' : 'Copy'}
                    </button>
                  </div>
                  <textarea
                    value={hashtags}
                    onChange={e => setHashtags(e.target.value)}
                    rows={3}
                    className="w-full rounded-lg border border-gray-200 px-3 py-2 text-sm text-blue-600 font-mono focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none"
                  />
                </div>

                <button
                  onClick={() => handleCopy(`${caption}\n\n${hashtags}`, 'all')}
                  className={cn(
                    'w-full h-9 rounded-lg border text-sm font-semibold transition-colors',
                    copied === 'all'
                      ? 'bg-green-50 border-green-200 text-green-700'
                      : 'bg-gray-50 border-gray-200 text-gray-700 hover:bg-gray-100',
                  )}
                >
                  {copied === 'all' ? 'Copied caption + hashtags!' : 'Copy All'}
                </button>
              </>
            )}
          </div>

          {/* Image */}
          <div className="space-y-3">
            {imageUrl ? (
              <div className="bg-white rounded-xl border border-gray-200 p-4">
                <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-3">Generated Image</p>
                <div className={cn(RATIO_CLASS[imageRatio] ?? 'aspect-square', 'rounded-xl overflow-hidden border border-gray-200 bg-gray-50')}>
                  <img src={imageUrl} alt="Generated" className="w-full h-full object-cover" />
                </div>
                <div className="flex gap-2 mt-3">
                  <a
                    href={imageUrl}
                    download
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-center gap-1 h-8 px-3 rounded-lg border border-gray-200 text-xs font-medium text-gray-700 hover:bg-gray-50"
                  >
                    <Download className="h-3 w-3" /> Download
                  </a>
                  <button
                    onClick={handleGenerate}
                    disabled={generating}
                    className="flex items-center gap-1 h-8 px-3 rounded-lg border border-gray-200 text-xs font-medium text-gray-700 hover:bg-gray-50 disabled:opacity-50"
                  >
                    <Sparkles className="h-3 w-3" /> Regenerate
                  </button>
                </div>
                {imagePrompt && (
                  <details className="mt-3">
                    <summary className="cursor-pointer text-[11px] font-medium text-gray-500 hover:text-gray-700">View image prompt</summary>
                    <pre className="mt-2 p-3 bg-gray-50 rounded-lg text-[10px] text-gray-600 whitespace-pre-wrap leading-relaxed max-h-48 overflow-y-auto">{imagePrompt}</pre>
                  </details>
                )}
              </div>
            ) : (
              <div className="bg-white rounded-xl border border-gray-200 p-4">
                <div className={cn(RATIO_CLASS[imageRatio] ?? 'aspect-square', 'rounded-xl border-2 border-dashed border-blue-200 flex flex-col items-center justify-center text-blue-400 bg-blue-50/30')}>
                  <Loader2 className="h-10 w-10 animate-spin mb-2" />
                  <p className="text-xs font-medium">Generating image…</p>
                  <p className="text-[10px] mt-1 text-blue-300">This may take 15–30 seconds</p>
                </div>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Empty state */}
      {!caption && !imageUrl && !generating && (
        <div className="bg-white rounded-xl border border-gray-200 p-12 text-center">
          <Sparkles className="h-8 w-8 text-gray-300 mx-auto mb-3" />
          <p className="text-sm text-gray-500">Select a calendar entry and click Generate</p>
          <p className="text-xs text-gray-400 mt-1">AI will create a caption, hashtags, and image together</p>
        </div>
      )}
    </div>
  )
}
